export const FETCH_POOLS_REQUEST = 'FETCH_POOLS_REQUEST';
export const FETCH_POOLS_SUCCESS = 'FETCH_POOLS_SUCCESS';
export const FETCH_POOLS_FAILURE = 'FETCH_POOLS_FAILURE';

export const CREATE_POOL_REQUEST = 'CREATE_POOL_REQUEST';
export const CREATE_POOL_SUCCESS = 'CREATE_POOL_SUCCESS';
export const CREATE_POOL_FAILURE = 'CREATE_POOL_FAILURE';

export const HANDLE_POOL_FIELD_CHANGE = 'HANDLE_POOL_FIELD_CHANGE';