export const FETCH_ACTIVE_USER_REQUEST = 'FETCH_ACTIVE_USER_REQUEST';
export const FETCH_ACTIVE_USER_SUCCESS = 'FETCH_ACTIVE_USER_SUCCESS';
export const FETCH_ACTIVE_USER_FAILURE = 'FETCH_ACTIVE_USER_FAILURE';